# Generated by Django 3.1.4 on 2021-02-05 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('paid', models.BooleanField(default=False)),
                ('currency', models.IntegerField(choices=[(0, 'CAD'), (1, 'USD'), (2, 'EUR'), (3, 'AUD'), (4, 'GBP'), (5, 'DKK'), (6, 'HKD'), (7, 'HUF'), (8, 'ILS'), (9, 'JPY'), (10, 'MXN'), (11, 'TWD'), (12, 'NZD'), (13, 'NOK'), (14, 'PHP'), (15, 'PLN'), (16, 'CZK'), (17, 'RUB'), (18, 'SGD'), (19, 'SEK'), (20, 'CHF'), (21, 'THB')], default=0)),
                ('description', models.CharField(default='Editing Services', max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
