# Generated by Django 3.1.4 on 2021-01-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210102_0447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
